glslc Metallic.frag -o MetallicFrag.spv
glslc Metallic.vert -o MetallicVert.spv
glslc Opaque.frag -o OpaqueFrag.spv
glslc Opaque.vert -o OpaqueVert.spv
glslc Overlay.frag -o OverlayFrag.spv
glslc Overlay.vert -o OverlayVert.spv
glslc Emit.frag -o EmitFrag.spv
glslc Emit.vert -o EmitVert.spv
glslc Animation.frag -o AnimationFrag.spv
glslc Animation.vert -o AnimationVert.spv